export interface Venue {
	id: number;
	hostName: string;
	location: string;
	city: string;
	seatsAvailable: number;
	totalSeats: number;
	gameStyle: string;
	timing: string;
	pricePerSession: number;
	rating: number;
	reviewCount: number;
	bookingType: 'instant' | 'approval' | 'waitlist';
	amenities: string[];
	description: string;
	hostType: 'home' | 'venue';
}

export const venues: Venue[] = [
	// Mumbai (15)
	{
		id: 1,
		hostName: 'Malini',
		location: 'Bandra 14th Rd, Mumbai',
		city: 'Mumbai',
		seatsAvailable: 1,
		totalSeats: 4,
		gameStyle: 'Casual HK style',
		timing: 'Evening game',
		pricePerSession: 950,
		rating: 4.8,
		reviewCount: 23,
		bookingType: 'instant',
		amenities: ['Tea/Coffee included', 'AC', 'Home-cooked snacks', 'Friendly atmosphere'],
		description: 'Cozy evening sessions with traditional Hong Kong style Mahjong',
		hostType: 'home'
	},
	{
		id: 2,
		hostName: 'Rohit',
		location: 'Colaba, Mumbai',
		city: 'Mumbai',
		seatsAvailable: 2,
		totalSeats: 4,
		gameStyle: 'Antique tiles set',
		timing: 'Afternoon game',
		pricePerSession: 1100,
		rating: 4.9,
		reviewCount: 45,
		bookingType: 'approval',
		amenities: ['Premium tea selection', 'Heritage tiles', 'South Mumbai charm', 'Parking available'],
		description: 'Experience Mahjong with beautiful antique tiles in heritage Colaba',
		hostType: 'home'
	},
	{
		id: 3,
		hostName: 'Neha',
		location: 'Powai Hiranandani, Mumbai',
		city: 'Mumbai',
		seatsAvailable: 0,
		totalSeats: 4,
		gameStyle: 'Taiwanese rules',
		timing: 'Evening sessions',
		pricePerSession: 1000,
		rating: 4.7,
		reviewCount: 67,
		bookingType: 'waitlist',
		amenities: ['Gourmet coffee', 'Modern apartment', 'City views', 'Taiwanese expertise'],
		description: 'Popular Taiwanese Mahjong sessions in modern Hiranandani complex',
		hostType: 'home'
	},
	{
		id: 4,
		hostName: 'Ramesh',
		location: 'Dadar Shivaji Park, Mumbai',
		city: 'Mumbai',
		seatsAvailable: 3,
		totalSeats: 4,
		gameStyle: 'Beginner-friendly',
		timing: 'Morning sessions',
		pricePerSession: 900,
		rating: 4.6,
		reviewCount: 34,
		bookingType: 'instant',
		amenities: ['Beginner guidance', 'Morning chai', 'Patient teaching', 'Central Mumbai'],
		description: 'Perfect for newcomers! Learn Mahjong in a welcoming environment',
		hostType: 'home'
	},
	{
		id: 5,
		hostName: 'Lalita',
		location: 'Worli Seaface, Mumbai',
		city: 'Mumbai',
		seatsAvailable: 2,
		totalSeats: 4,
		gameStyle: 'Automatic table',
		timing: 'Friday nights',
		pricePerSession: 1150,
		rating: 4.8,
		reviewCount: 52,
		bookingType: 'approval',
		amenities: ['Automatic table', 'Sea views', 'Premium setup', 'Weekend vibes'],
		description: 'Luxury Friday night sessions with stunning sea views',
		hostType: 'home'
	},
	{
		id: 6,
		hostName: 'Sana',
		location: 'Versova, Mumbai',
		city: 'Mumbai',
		seatsAvailable: 1,
		totalSeats: 4,
		gameStyle: 'Snacks + Mahjong',
		timing: 'Saturday brunch',
		pricePerSession: 1200,
		rating: 4.9,
		reviewCount: 78,
		bookingType: 'instant',
		amenities: ['Brunch included', 'Homemade snacks', 'Weekend relaxation', 'Versova charm'],
		description: 'Delightful Saturday brunch combined with friendly Mahjong',
		hostType: 'home'
	},
	{
		id: 7,
		hostName: 'Deepak',
		location: 'Juhu Scheme, Mumbai',
		city: 'Mumbai',
		seatsAvailable: 2,
		totalSeats: 4,
		gameStyle: 'Fast-paced Riichi',
		timing: 'Evening sessions',
		pricePerSession: 980,
		rating: 4.7,
		reviewCount: 41,
		bookingType: 'instant',
		amenities: ['Quick gameplay', 'Energetic atmosphere', 'Juhu location', 'Expert players'],
		description: 'High-energy Riichi sessions for experienced players',
		hostType: 'home'
	},
	{
		id: 8,
		hostName: 'Anjali',
		location: 'Malabar Hill, Mumbai',
		city: 'Mumbai',
		seatsAvailable: 0,
		totalSeats: 4,
		gameStyle: 'Luxury teakwood set',
		timing: 'Exclusive sessions',
		pricePerSession: 1200,
		rating: 5.0,
		reviewCount: 29,
		bookingType: 'waitlist',
		amenities: ['Teakwood tiles', 'Luxury setting', 'Malabar Hill views', 'Premium experience'],
		description: 'Exclusive Mahjong experience with handcrafted teakwood set',
		hostType: 'home'
	},
	{
		id: 9,
		hostName: 'Vikram',
		location: 'BKC Residences, Mumbai',
		city: 'Mumbai',
		seatsAvailable: 3,
		totalSeats: 4,
		gameStyle: 'Corporate game',
		timing: 'Quick play sessions',
		pricePerSession: 1050,
		rating: 4.5,
		reviewCount: 38,
		bookingType: 'instant',
		amenities: ['Business district', 'Professional crowd', 'Quick sessions', 'Modern setup'],
		description: 'Perfect for busy professionals seeking quick Mahjong sessions',
		hostType: 'home'
	},
	{
		id: 10,
		hostName: 'Meher',
		location: 'Breach Candy, Mumbai',
		city: 'Mumbai',
		seatsAvailable: 2,
		totalSeats: 4,
		gameStyle: 'Mahjong & wine evening',
		timing: 'Evening sessions',
		pricePerSession: 1180,
		rating: 4.8,
		reviewCount: 56,
		bookingType: 'approval',
		amenities: ['Wine included', 'Elegant setting', 'South Mumbai', 'Sophisticated crowd'],
		description: 'Elegant evening sessions with wine and sophisticated gameplay',
		hostType: 'home'
	},
	{
		id: 11,
		hostName: 'Aditya',
		location: 'Bandra Reclamation, Mumbai',
		city: 'Mumbai',
		seatsAvailable: 1,
		totalSeats: 4,
		gameStyle: 'Friendly cash points',
		timing: 'Weekend sessions',
		pricePerSession: 950,
		rating: 4.6,
		reviewCount: 42,
		bookingType: 'instant',
		amenities: ['Casual atmosphere', 'Small stakes', 'Weekend fun', 'Bandra location'],
		description: 'Relaxed weekend sessions with friendly competition',
		hostType: 'home'
	},
	{
		id: 12,
		hostName: 'Sunita',
		location: 'Matunga East, Mumbai',
		city: 'Mumbai',
		seatsAvailable: 2,
		totalSeats: 4,
		gameStyle: 'Family vibe',
		timing: 'Sunday morning',
		pricePerSession: 900,
		rating: 4.7,
		reviewCount: 61,
		bookingType: 'instant',
		amenities: ['Family atmosphere', 'Sunday brunch', 'Homely setting', 'Traditional values'],
		description: 'Warm family-style Sunday morning sessions with homemade treats',
		hostType: 'home'
	},
	{
		id: 13,
		hostName: 'Ritu',
		location: 'Lokhandwala, Mumbai',
		city: 'Mumbai',
		seatsAvailable: 3,
		totalSeats: 4,
		gameStyle: 'Riichi beginners welcome',
		timing: 'Evening sessions',
		pricePerSession: 920,
		rating: 4.5,
		reviewCount: 27,
		bookingType: 'instant',
		amenities: ['Beginner friendly', 'Patient teaching', 'Andheri area', 'Learning focus'],
		description: 'Learn Japanese Riichi in a supportive, encouraging environment',
		hostType: 'home'
	},
	{
		id: 14,
		hostName: 'Kavita',
		location: 'Chembur Diamond Garden, Mumbai',
		city: 'Mumbai',
		seatsAvailable: 1,
		totalSeats: 4,
		gameStyle: 'Taiwanese',
		timing: 'Thursday evenings',
		pricePerSession: 980,
		rating: 4.8,
		reviewCount: 35,
		bookingType: 'approval',
		amenities: ['Taiwanese expertise', 'Regular group', 'Thursday tradition', 'East Mumbai'],
		description: 'Join our regular Thursday Taiwanese Mahjong circle',
		hostType: 'home'
	},
	{
		id: 15,
		hostName: 'Arjun',
		location: 'Santacruz East, Mumbai',
		city: 'Mumbai',
		seatsAvailable: 2,
		totalSeats: 4,
		gameStyle: 'Hybrid scoring',
		timing: 'Flexible timings',
		pricePerSession: 960,
		rating: 4.6,
		reviewCount: 48,
		bookingType: 'instant',
		amenities: ['Flexible rules', 'Airport area', 'Adaptable gameplay', 'Mixed styles'],
		description: 'Flexible Mahjong sessions accommodating different playing styles',
		hostType: 'home'
	},
	// Delhi NCR (12) - Adding a few key ones for space
	{
		id: 16,
		hostName: 'Radhika',
		location: 'Hauz Khas Village, Delhi',
		city: 'Delhi',
		seatsAvailable: 2,
		totalSeats: 4,
		gameStyle: 'Riichi rules',
		timing: 'Evening chai sessions',
		pricePerSession: 950,
		rating: 4.7,
		reviewCount: 53,
		bookingType: 'instant',
		amenities: ['Evening chai', 'Village vibes', 'Cultural setting', 'Artistic crowd'],
		description: 'Charming Riichi sessions in the heart of Hauz Khas Village',
		hostType: 'home'
	},
	{
		id: 17,
		hostName: 'Siddharth',
		location: 'Greater Kailash II, Delhi',
		city: 'Delhi',
		seatsAvailable: 1,
		totalSeats: 4,
		gameStyle: 'Tournament prep',
		timing: 'Intensive sessions',
		pricePerSession: 1100,
		rating: 4.9,
		reviewCount: 67,
		bookingType: 'approval',
		amenities: ['Tournament focus', 'Competitive level', 'GK location', 'Serious gameplay'],
		description: 'Intensive sessions for tournament preparation and competitive play',
		hostType: 'home'
	},
	// Continue with more cities...
	{
		id: 18,
		hostName: 'Shruti',
		location: 'Indiranagar 100 ft Rd, Bangalore',
		city: 'Bangalore',
		seatsAvailable: 2,
		totalSeats: 4,
		gameStyle: 'Café Mahjong',
		timing: 'Afternoon sessions',
		pricePerSession: 950,
		rating: 4.6,
		reviewCount: 89,
		bookingType: 'instant',
		amenities: ['Café atmosphere', 'Indiranagar buzz', 'Coffee included', 'Casual vibe'],
		description: 'Relaxed café-style Mahjong in the heart of Indiranagar',
		hostType: 'home'
	},
	// More Delhi Venues
	{
		id: 19,
		hostName: 'Priya',
		location: 'Lajpat Nagar Central Market, Delhi',
		city: 'Delhi',
		seatsAvailable: 3,
		totalSeats: 4,
		gameStyle: 'Casual mixed rules',
		timing: 'Weekend mornings',
		pricePerSession: 900,
		rating: 4.5,
		reviewCount: 32,
		bookingType: 'instant',
		amenities: ['Weekend brunch', 'Market location', 'Mixed rules', 'Beginner friendly'],
		description: 'Casual weekend sessions with delicious brunch in bustling Lajpat Nagar',
		hostType: 'home'
	},
	{
		id: 20,
		hostName: 'Aman',
		location: 'DLF Phase 1, Gurgaon',
		city: 'Gurgaon',
		seatsAvailable: 1,
		totalSeats: 4,
		gameStyle: 'Corporate friendly',
		timing: 'Evening after work',
		pricePerSession: 1050,
		rating: 4.6,
		reviewCount: 41,
		bookingType: 'approval',
		amenities: ['Corporate crowd', 'Evening sessions', 'Professional setup', 'Gurgaon location'],
		description: 'Perfect for working professionals - unwind with Mahjong after work',
		hostType: 'home'
	},
	// More Bangalore Venues
	{
		id: 21,
		hostName: 'Kavya',
		location: 'Koramangala 5th Block, Bangalore',
		city: 'Bangalore',
		seatsAvailable: 2,
		totalSeats: 4,
		gameStyle: 'Tech crowd favorite',
		timing: 'Weekend evenings',
		pricePerSession: 980,
		rating: 4.7,
		reviewCount: 58,
		bookingType: 'instant',
		amenities: ['Tech-savvy crowd', 'Modern setup', 'Weekend vibes', 'Koramangala buzz'],
		description: 'Popular among Bangalore\'s tech community for weekend Mahjong sessions',
		hostType: 'home'
	},
	{
		id: 22,
		hostName: 'Rajesh',
		location: 'Whitefield IT Park Area, Bangalore',
		city: 'Bangalore',
		seatsAvailable: 3,
		totalSeats: 4,
		gameStyle: 'Quick evening games',
		timing: 'Weekday evenings',
		pricePerSession: 950,
		rating: 4.4,
		reviewCount: 29,
		bookingType: 'instant',
		amenities: ['IT Park area', 'Quick sessions', 'Weekday availability', 'Tech professionals'],
		description: 'Convenient location for IT professionals, quick weekday evening games',
		hostType: 'home'
	},
	// Pune Venues
	{
		id: 23,
		hostName: 'Sneha',
		location: 'Koregaon Park, Pune',
		city: 'Pune',
		seatsAvailable: 1,
		totalSeats: 4,
		gameStyle: 'Classic HK style',
		timing: 'Saturday afternoons',
		pricePerSession: 920,
		rating: 4.8,
		reviewCount: 47,
		bookingType: 'approval',
		amenities: ['Koregaon Park', 'Classic style', 'Saturday tradition', 'Premium location'],
		description: 'Elegant Saturday afternoon sessions in upscale Koregaon Park',
		hostType: 'home'
	},
	{
		id: 24,
		hostName: 'Amit',
		location: 'Baner IT Hub, Pune',
		city: 'Pune',
		seatsAvailable: 2,
		totalSeats: 4,
		gameStyle: 'Modern Riichi',
		timing: 'Sunday morning',
		pricePerSession: 900,
		rating: 4.5,
		reviewCount: 35,
		bookingType: 'instant',
		amenities: ['IT Hub area', 'Modern rules', 'Sunday brunch', 'Young crowd'],
		description: 'Modern Riichi sessions with Sunday brunch in Baner IT Hub',
		hostType: 'home'
	},
	{
		id: 25,
		hostName: 'Pooja',
		location: 'Viman Nagar, Pune',
		city: 'Pune',
		seatsAvailable: 0,
		totalSeats: 4,
		gameStyle: 'Ladies special',
		timing: 'Weekday mornings',
		pricePerSession: 880,
		rating: 4.9,
		reviewCount: 64,
		bookingType: 'waitlist',
		amenities: ['Ladies only', 'Morning sessions', 'Safe space', 'Regular group'],
		description: 'Popular ladies-only morning sessions in a comfortable home setting',
		hostType: 'home'
	},
	// Hyderabad Venues
	{
		id: 26,
		hostName: 'Srinivas',
		location: 'Jubilee Hills, Hyderabad',
		city: 'Hyderabad',
		seatsAvailable: 2,
		totalSeats: 4,
		gameStyle: 'Traditional Telugu style',
		timing: 'Evening sessions',
		pricePerSession: 950,
		rating: 4.6,
		reviewCount: 38,
		bookingType: 'instant',
		amenities: ['Jubilee Hills', 'Telugu traditions', 'Evening chai', 'Cultural setting'],
		description: 'Traditional Telugu-style Mahjong in the prestigious Jubilee Hills',
		hostType: 'home'
	},
	{
		id: 27,
		hostName: 'Lakshmi',
		location: 'Gachibowli IT Corridor, Hyderabad',
		city: 'Hyderabad',
		seatsAvailable: 3,
		totalSeats: 4,
		gameStyle: 'Modern quick play',
		timing: 'Weekend mornings',
		pricePerSession: 920,
		rating: 4.4,
		reviewCount: 26,
		bookingType: 'instant',
		amenities: ['IT Corridor', 'Quick games', 'Weekend availability', 'Modern setup'],
		description: 'Modern quick-play sessions for busy IT professionals',
		hostType: 'home'
	},
	// Chennai Venues
	{
		id: 28,
		hostName: 'Priya',
		location: 'T. Nagar Shopping District, Chennai',
		city: 'Chennai',
		seatsAvailable: 1,
		totalSeats: 4,
		gameStyle: 'South Indian style',
		timing: 'Afternoon sessions',
		pricePerSession: 900,
		rating: 4.7,
		reviewCount: 43,
		bookingType: 'approval',
		amenities: ['T. Nagar location', 'South Indian style', 'Traditional setup', 'Shopping nearby'],
		description: 'Authentic South Indian Mahjong in the heart of T. Nagar',
		hostType: 'home'
	},
	{
		id: 29,
		hostName: 'Karthik',
		location: 'Adyar Riverside, Chennai',
		city: 'Chennai',
		seatsAvailable: 2,
		totalSeats: 4,
		gameStyle: 'Riverside relaxed',
		timing: 'Evening breeze sessions',
		pricePerSession: 940,
		rating: 4.8,
		reviewCount: 51,
		bookingType: 'instant',
		amenities: ['Riverside location', 'Evening breeze', 'Relaxed atmosphere', 'Nature views'],
		description: 'Serene riverside Mahjong sessions with the evening breeze',
		hostType: 'home'
	},
	// Kolkata Venues
	{
		id: 30,
		hostName: 'Ritupriya',
		location: 'Park Street Cultural Hub, Kolkata',
		city: 'Kolkata',
		seatsAvailable: 1,
		totalSeats: 4,
		gameStyle: 'Bengali intellectual',
		timing: 'Evening cultural sessions',
		pricePerSession: 920,
		rating: 4.9,
		reviewCount: 67,
		bookingType: 'approval',
		amenities: ['Park Street', 'Cultural crowd', 'Intellectual discussions', 'Historic setting'],
		description: 'Cultural evening sessions with Bengali intellectuals and artists',
		hostType: 'home'
	},
	{
		id: 31,
		hostName: 'Soumitra',
		location: 'Salt Lake Sector V, Kolkata',
		city: 'Kolkata',
		seatsAvailable: 3,
		totalSeats: 4,
		gameStyle: 'IT professional friendly',
		timing: 'Weekend sessions',
		pricePerSession: 900,
		rating: 4.5,
		reviewCount: 31,
		bookingType: 'instant',
		amenities: ['Sector V IT hub', 'Professional crowd', 'Weekend availability', 'Modern approach'],
		description: 'Modern Mahjong sessions for IT professionals in Salt Lake',
		hostType: 'home'
	},
	// Goa Venues
	{
		id: 32,
		hostName: 'Maria',
		location: 'Anjuna Beach Road, Goa',
		city: 'Goa',
		seatsAvailable: 2,
		totalSeats: 4,
		gameStyle: 'Beach relaxed',
		timing: 'Sunset sessions',
		pricePerSession: 1100,
		rating: 4.8,
		reviewCount: 55,
		bookingType: 'instant',
		amenities: ['Beach proximity', 'Sunset timing', 'Relaxed vibe', 'Tourist friendly'],
		description: 'Magical sunset Mahjong sessions near beautiful Anjuna Beach',
		hostType: 'home'
	},
	{
		id: 33,
		hostName: 'Carlos',
		location: 'Fontainhas Latin Quarter, Panaji, Goa',
		city: 'Goa',
		seatsAvailable: 1,
		totalSeats: 4,
		gameStyle: 'Portuguese heritage',
		timing: 'Heritage morning sessions',
		pricePerSession: 1050,
		rating: 4.9,
		reviewCount: 48,
		bookingType: 'approval',
		amenities: ['Heritage quarter', 'Portuguese influence', 'Cultural setting', 'Historic charm'],
		description: 'Unique heritage Mahjong in the colorful Portuguese quarter',
		hostType: 'home'
	},
	// Ahmedabad Venues
	{
		id: 34,
		hostName: 'Bhavna',
		location: 'Vastrapur Business District, Ahmedabad',
		city: 'Ahmedabad',
		seatsAvailable: 2,
		totalSeats: 4,
		gameStyle: 'Gujarati style',
		timing: 'Evening sessions',
		pricePerSession: 900,
		rating: 4.6,
		reviewCount: 42,
		bookingType: 'instant',
		amenities: ['Business district', 'Gujarati traditions', 'Evening snacks', 'Local flavor'],
		description: 'Traditional Gujarati-style Mahjong with local snacks and traditions',
		hostType: 'home'
	},
	{
		id: 35,
		hostName: 'Kiran',
		location: 'Satellite IT Hub, Ahmedabad',
		city: 'Ahmedabad',
		seatsAvailable: 3,
		totalSeats: 4,
		gameStyle: 'Modern corporate',
		timing: 'Weekend mornings',
		pricePerSession: 920,
		rating: 4.4,
		reviewCount: 28,
		bookingType: 'instant',
		amenities: ['IT Hub area', 'Corporate crowd', 'Weekend sessions', 'Modern setup'],
		description: 'Modern corporate-style sessions for Ahmedabad\'s IT professionals',
		hostType: 'home'
	},
	// Alibaug Venues
	{
		id: 36,
		hostName: 'Asha',
		location: 'Alibaug Beach Resort Area',
		city: 'Alibaug',
		seatsAvailable: 1,
		totalSeats: 4,
		gameStyle: 'Coastal retreat',
		timing: 'Weekend getaway sessions',
		pricePerSession: 1200,
		rating: 4.9,
		reviewCount: 39,
		bookingType: 'approval',
		amenities: ['Beach resort', 'Weekend getaway', 'Coastal views', 'Retreat atmosphere'],
		description: 'Perfect weekend getaway Mahjong sessions with stunning coastal views',
		hostType: 'home'
	},
	// Additional Mumbai venues (to reach 72 total)
	{
		id: 37,
		hostName: 'Nisha',
		location: 'Linking Road, Bandra West, Mumbai',
		city: 'Mumbai',
		seatsAvailable: 2,
		totalSeats: 4,
		gameStyle: 'Shopping district special',
		timing: 'Weekend afternoons',
		pricePerSession: 980,
		rating: 4.6,
		reviewCount: 44,
		bookingType: 'instant',
		amenities: ['Shopping area', 'Weekend sessions', 'Bandra buzz', 'Fashion district'],
		description: 'Trendy weekend sessions in Mumbai\'s famous shopping district',
		hostType: 'home'
	},
	{
		id: 38,
		hostName: 'Rajiv',
		location: 'Marine Drive Vicinity, Mumbai',
		city: 'Mumbai',
		seatsAvailable: 1,
		totalSeats: 4,
		gameStyle: 'Queen\'s Necklace special',
		timing: 'Evening sea breeze',
		pricePerSession: 1150,
		rating: 4.9,
		reviewCount: 58,
		bookingType: 'approval',
		amenities: ['Marine Drive', 'Sea breeze', 'Iconic location', 'Evening sessions'],
		description: 'Iconic Mumbai experience with sea breeze and city lights',
		hostType: 'home'
	},
	{
		id: 39,
		hostName: 'Swapna',
		location: 'Thane West Station Area, Mumbai',
		city: 'Mumbai',
		seatsAvailable: 3,
		totalSeats: 4,
		gameStyle: 'Suburban family style',
		timing: 'Family evening sessions',
		pricePerSession: 900,
		rating: 4.7,
		reviewCount: 46,
		bookingType: 'instant',
		amenities: ['Thane area', 'Family atmosphere', 'Suburban charm', 'Regular group'],
		description: 'Warm family-style sessions in Mumbai\'s suburban Thane area',
		hostType: 'home'
	},
	{
		id: 40,
		hostName: 'Manish',
		location: 'Andheri Film City Area, Mumbai',
		city: 'Mumbai',
		seatsAvailable: 2,
		totalSeats: 4,
		gameStyle: 'Film industry crowd',
		timing: 'Late night sessions',
		pricePerSession: 1100,
		rating: 4.8,
		reviewCount: 52,
		bookingType: 'approval',
		amenities: ['Film City area', 'Entertainment industry', 'Late night', 'Creative crowd'],
		description: 'Late night sessions popular with Mumbai\'s film and TV professionals',
		hostType: 'home'
	},
	// Additional Delhi venues
	{
		id: 41,
		hostName: 'Anita',
		location: 'Khan Market, Delhi',
		city: 'Delhi',
		seatsAvailable: 1,
		totalSeats: 4,
		gameStyle: 'Upscale market area',
		timing: 'Weekend brunches',
		pricePerSession: 1050,
		rating: 4.7,
		reviewCount: 41,
		bookingType: 'approval',
		amenities: ['Khan Market', 'Upscale setting', 'Weekend brunch', 'Premium crowd'],
		description: 'Upscale weekend brunch sessions in Delhi\'s premium Khan Market',
		hostType: 'home'
	},
	{
		id: 42,
		hostName: 'Rohit',
		location: 'CP Connaught Place Area, Delhi',
		city: 'Delhi',
		seatsAvailable: 2,
		totalSeats: 4,
		gameStyle: 'Central Delhi hub',
		timing: 'Evening sessions',
		pricePerSession: 980,
		rating: 4.5,
		reviewCount: 37,
		bookingType: 'instant',
		amenities: ['Connaught Place', 'Central location', 'Evening sessions', 'Metro accessible'],
		description: 'Centrally located sessions in the heart of Delhi\'s business district',
		hostType: 'home'
	},
	{
		id: 43,
		hostName: 'Neerja',
		location: 'Karol Bagh Shopping Area, Delhi',
		city: 'Delhi',
		seatsAvailable: 3,
		totalSeats: 4,
		gameStyle: 'Traditional Delhi',
		timing: 'Morning sessions',
		pricePerSession: 920,
		rating: 4.6,
		reviewCount: 33,
		bookingType: 'instant',
		amenities: ['Karol Bagh', 'Traditional Delhi', 'Morning chai', 'Shopping nearby'],
		description: 'Traditional Delhi-style morning sessions in bustling Karol Bagh',
		hostType: 'home'
	},
	// Additional Bangalore venues
	{
		id: 44,
		hostName: 'Arjun',
		location: 'MG Road Brigade Area, Bangalore',
		city: 'Bangalore',
		seatsAvailable: 1,
		totalSeats: 4,
		gameStyle: 'Central business district',
		timing: 'Weekend evenings',
		pricePerSession: 1000,
		rating: 4.7,
		reviewCount: 45,
		bookingType: 'approval',
		amenities: ['MG Road', 'Business district', 'Weekend sessions', 'Urban crowd'],
		description: 'Upscale sessions in Bangalore\'s premier business district',
		hostType: 'home'
	},
	{
		id: 45,
		hostName: 'Deepika',
		location: 'HSR Layout Sector 7, Bangalore',
		city: 'Bangalore',
		seatsAvailable: 2,
		totalSeats: 4,
		gameStyle: 'Young professional',
		timing: 'Sunday afternoon',
		pricePerSession: 950,
		rating: 4.5,
		reviewCount: 39,
		bookingType: 'instant',
		amenities: ['HSR Layout', 'Young crowd', 'Sunday sessions', 'Modern locality'],
		description: 'Sunday afternoon sessions popular with young Bangalore professionals',
		hostType: 'home'
	},
	{
		id: 46,
		hostName: 'Manoj',
		location: 'BTM Layout 2nd Stage, Bangalore',
		city: 'Bangalore',
		seatsAvailable: 3,
		totalSeats: 4,
		gameStyle: 'South Bangalore special',
		timing: 'Evening sessions',
		pricePerSession: 920,
		rating: 4.4,
		reviewCount: 27,
		bookingType: 'instant',
		amenities: ['BTM Layout', 'South Bangalore', 'Regular group', 'Evening timing'],
		description: 'Regular evening group sessions in popular BTM Layout area',
		hostType: 'home'
	},
	// Additional Pune venues
	{
		id: 47,
		hostName: 'Shilpa',
		location: 'FC Road Camp Area, Pune',
		city: 'Pune',
		seatsAvailable: 1,
		totalSeats: 4,
		gameStyle: 'College crowd favorite',
		timing: 'Weekend afternoons',
		pricePerSession: 900,
		rating: 4.6,
		reviewCount: 42,
		bookingType: 'instant',
		amenities: ['FC Road', 'College area', 'Weekend sessions', 'Young crowd'],
		description: 'Popular weekend spot for Pune\'s college crowd and young professionals',
		hostType: 'home'
	},
	{
		id: 48,
		hostName: 'Prasad',
		location: 'Deccan Gymkhana, Pune',
		city: 'Pune',
		seatsAvailable: 2,
		totalSeats: 4,
		gameStyle: 'Traditional Pune',
		timing: 'Morning sessions',
		pricePerSession: 920,
		rating: 4.7,
		reviewCount: 48,
		bookingType: 'approval',
		amenities: ['Deccan area', 'Traditional Pune', 'Morning sessions', 'Cultural crowd'],
		description: 'Traditional Pune-style morning sessions in cultural Deccan area',
		hostType: 'home'
	},
	// Additional Hyderabad venues
	{
		id: 49,
		hostName: 'Ramya',
		location: 'Banjara Hills Road 12, Hyderabad',
		city: 'Hyderabad',
		seatsAvailable: 1,
		totalSeats: 4,
		gameStyle: 'Upscale Hyderabad',
		timing: 'Weekend evenings',
		pricePerSession: 1000,
		rating: 4.8,
		reviewCount: 44,
		bookingType: 'approval',
		amenities: ['Banjara Hills', 'Upscale area', 'Weekend evenings', 'Premium setting'],
		description: 'Premium weekend sessions in upscale Banjara Hills area',
		hostType: 'home'
	},
	{
		id: 50,
		hostName: 'Venkat',
		location: 'Madhapur HITEC City, Hyderabad',
		city: 'Hyderabad',
		seatsAvailable: 3,
		totalSeats: 4,
		gameStyle: 'Tech hub sessions',
		timing: 'Weekday evenings',
		pricePerSession: 940,
		rating: 4.5,
		reviewCount: 31,
		bookingType: 'instant',
		amenities: ['HITEC City', 'Tech professionals', 'Weekday evenings', 'Modern setup'],
		description: 'Weekday evening sessions for HITEC City tech professionals',
		hostType: 'home'
	},
	// Additional Chennai venues
	{
		id: 51,
		hostName: 'Meera',
		location: 'Besant Nagar Beach Area, Chennai',
		city: 'Chennai',
		seatsAvailable: 2,
		totalSeats: 4,
		gameStyle: 'Beachside relaxed',
		timing: 'Evening sea breeze',
		pricePerSession: 960,
		rating: 4.8,
		reviewCount: 47,
		bookingType: 'instant',
		amenities: ['Beach area', 'Sea breeze', 'Evening sessions', 'Relaxed vibe'],
		description: 'Relaxing evening sessions with Chennai\'s famous sea breeze',
		hostType: 'home'
	},
	{
		id: 52,
		hostName: 'Sanjay',
		location: 'OMR IT Corridor, Chennai',
		city: 'Chennai',
		seatsAvailable: 3,
		totalSeats: 4,
		gameStyle: 'IT professional hub',
		timing: 'Weekend mornings',
		pricePerSession: 920,
		rating: 4.4,
		reviewCount: 34,
		bookingType: 'instant',
		amenities: ['OMR IT corridor', 'Tech professionals', 'Weekend sessions', 'Modern approach'],
		description: 'Weekend morning sessions for Chennai\'s IT corridor professionals',
		hostType: 'home'
	},
	// Additional Kolkata venues
	{
		id: 53,
		hostName: 'Sukanya',
		location: 'Ballygunge Cultural Area, Kolkata',
		city: 'Kolkata',
		seatsAvailable: 1,
		totalSeats: 4,
		gameStyle: 'Cultural Bengali',
		timing: 'Sunday afternoon',
		pricePerSession: 940,
		rating: 4.9,
		reviewCount: 56,
		bookingType: 'approval',
		amenities: ['Ballygunge', 'Cultural area', 'Sunday tradition', 'Bengali heritage'],
		description: 'Traditional Sunday afternoon sessions in Kolkata\'s cultural Ballygunge',
		hostType: 'home'
	},
	{
		id: 54,
		hostName: 'Debashish',
		location: 'New Town Action Area, Kolkata',
		city: 'Kolkata',
		seatsAvailable: 2,
		totalSeats: 4,
		gameStyle: 'Modern Kolkata',
		timing: 'Evening sessions',
		pricePerSession: 920,
		rating: 4.5,
		reviewCount: 33,
		bookingType: 'instant',
		amenities: ['New Town', 'Modern area', 'Evening sessions', 'Contemporary crowd'],
		description: 'Modern sessions in Kolkata\'s contemporary New Town development',
		hostType: 'home'
	},
	// Additional venues across other cities
	{
		id: 55,
		hostName: 'Ravi',
		location: 'Jaipur Pink City, Rajasthan',
		city: 'Jaipur',
		seatsAvailable: 2,
		totalSeats: 4,
		gameStyle: 'Rajasthani royal',
		timing: 'Heritage evening sessions',
		pricePerSession: 980,
		rating: 4.7,
		reviewCount: 38,
		bookingType: 'approval',
		amenities: ['Pink City', 'Royal heritage', 'Traditional setting', 'Cultural experience'],
		description: 'Royal heritage sessions in the majestic Pink City of Jaipur',
		hostType: 'home'
	},
	{
		id: 56,
		hostName: 'Ashok',
		location: 'Lucknow Hazratganj, UP',
		city: 'Lucknow',
		seatsAvailable: 3,
		totalSeats: 4,
		gameStyle: 'Nawabi style',
		timing: 'Evening nawabi sessions',
		pricePerSession: 950,
		rating: 4.6,
		reviewCount: 29,
		bookingType: 'instant',
		amenities: ['Hazratganj', 'Nawabi culture', 'Evening sessions', 'Traditional hospitality'],
		description: 'Elegant Nawabi-style sessions with traditional Lucknow hospitality',
		hostType: 'home'
	},
	{
		id: 57,
		hostName: 'Preeti',
		location: 'Chandigarh Sector 17, Punjab',
		city: 'Chandigarh',
		seatsAvailable: 1,
		totalSeats: 4,
		gameStyle: 'Punjabi enthusiastic',
		timing: 'Weekend family sessions',
		pricePerSession: 920,
		rating: 4.8,
		reviewCount: 41,
		bookingType: 'instant',
		amenities: ['Sector 17', 'Punjabi warmth', 'Family atmosphere', 'Weekend sessions'],
		description: 'Warm Punjabi hospitality with enthusiastic weekend family sessions',
		hostType: 'home'
	},
	{
		id: 58,
		hostName: 'Gopal',
		location: 'Indore Vijay Nagar, MP',
		city: 'Indore',
		seatsAvailable: 2,
		totalSeats: 4,
		gameStyle: 'Central India style',
		timing: 'Evening sessions',
		pricePerSession: 900,
		rating: 4.5,
		reviewCount: 26,
		bookingType: 'instant',
		amenities: ['Vijay Nagar', 'Central India', 'Evening sessions', 'Local traditions'],
		description: 'Traditional Central Indian Mahjong in the commercial hub of Indore',
		hostType: 'home'
	},
	{
		id: 59,
		hostName: 'Kavitha',
		location: 'Kochi Marine Drive, Kerala',
		city: 'Kochi',
		seatsAvailable: 1,
		totalSeats: 4,
		gameStyle: 'Kerala backwater',
		timing: 'Backwater evening',
		pricePerSession: 980,
		rating: 4.9,
		reviewCount: 44,
		bookingType: 'approval',
		amenities: ['Marine Drive', 'Backwater views', 'Kerala charm', 'Scenic setting'],
		description: 'Scenic backwater sessions with Kerala\'s natural beauty and charm',
		hostType: 'home'
	},
	{
		id: 60,
		hostName: 'Rajesh',
		location: 'Bhubaneswar Temple City, Odisha',
		city: 'Bhubaneswar',
		seatsAvailable: 3,
		totalSeats: 4,
		gameStyle: 'Temple city spiritual',
		timing: 'Morning spiritual sessions',
		pricePerSession: 890,
		rating: 4.6,
		reviewCount: 31,
		bookingType: 'instant',
		amenities: ['Temple city', 'Spiritual atmosphere', 'Morning sessions', 'Cultural heritage'],
		description: 'Peaceful morning sessions in Odisha\'s spiritual temple city',
		hostType: 'home'
	},
	{
		id: 61,
		hostName: 'Suresh',
		location: 'Nagpur Orange City, Maharashtra',
		city: 'Nagpur',
		seatsAvailable: 2,
		totalSeats: 4,
		gameStyle: 'Central Maharashtra',
		timing: 'Weekend sessions',
		pricePerSession: 910,
		rating: 4.4,
		reviewCount: 25,
		bookingType: 'instant',
		amenities: ['Orange City', 'Central location', 'Weekend availability', 'Local culture'],
		description: 'Weekend sessions in Maharashtra\'s geographical center, Nagpur',
		hostType: 'home'
	},
	{
		id: 62,
		hostName: 'Anurag',
		location: 'Dehradun Hill Station, Uttarakhand',
		city: 'Dehradun',
		seatsAvailable: 1,
		totalSeats: 4,
		gameStyle: 'Hill station retreat',
		timing: 'Mountain evening',
		pricePerSession: 950,
		rating: 4.8,
		reviewCount: 36,
		bookingType: 'approval',
		amenities: ['Hill station', 'Mountain views', 'Cool climate', 'Retreat setting'],
		description: 'Refreshing mountain evening sessions in beautiful Dehradun hills',
		hostType: 'home'
	},
	{
		id: 63,
		hostName: 'Priyanka',
		location: 'Coimbatore Textile City, Tamil Nadu',
		city: 'Coimbatore',
		seatsAvailable: 2,
		totalSeats: 4,
		gameStyle: 'Industrial city',
		timing: 'Evening sessions',
		pricePerSession: 920,
		rating: 4.5,
		reviewCount: 32,
		bookingType: 'instant',
		amenities: ['Textile city', 'Industrial area', 'Evening sessions', 'Business crowd'],
		description: 'Evening sessions for Coimbatore\'s industrious business community',
		hostType: 'home'
	},
	{
		id: 64,
		hostName: 'Vikram',
		location: 'Mysore Palace City, Karnataka',
		city: 'Mysore',
		seatsAvailable: 1,
		totalSeats: 4,
		gameStyle: 'Royal Mysore',
		timing: 'Palace heritage sessions',
		pricePerSession: 960,
		rating: 4.7,
		reviewCount: 39,
		bookingType: 'approval',
		amenities: ['Palace city', 'Royal heritage', 'Cultural setting', 'Historic charm'],
		description: 'Royal heritage sessions in the magnificent Palace City of Mysore',
		hostType: 'home'
	},
	{
		id: 65,
		hostName: 'Madhuri',
		location: 'Vadodara Cultural City, Gujarat',
		city: 'Vadodara',
		seatsAvailable: 3,
		totalSeats: 4,
		gameStyle: 'Gujarati cultural',
		timing: 'Cultural evening',
		pricePerSession: 900,
		rating: 4.6,
		reviewCount: 27,
		bookingType: 'instant',
		amenities: ['Cultural city', 'Gujarati traditions', 'Evening sessions', 'Arts crowd'],
		description: 'Cultural evening sessions in Gujarat\'s art and culture hub Vadodara',
		hostType: 'home'
	},
	{
		id: 66,
		hostName: 'Ajay',
		location: 'Visakhapatnam Beach City, Andhra Pradesh',
		city: 'Visakhapatnam',
		seatsAvailable: 2,
		totalSeats: 4,
		gameStyle: 'Coastal Andhra',
		timing: 'Beach evening',
		pricePerSession: 930,
		rating: 4.7,
		reviewCount: 35,
		bookingType: 'instant',
		amenities: ['Beach city', 'Coastal views', 'Evening sessions', 'Sea breeze'],
		description: 'Coastal evening sessions with Visakhapatnam\'s beautiful beach views',
		hostType: 'home'
	},
	{
		id: 67,
		hostName: 'Sunanda',
		location: 'Guwahati Assam Tea Gardens',
		city: 'Guwahati',
		seatsAvailable: 1,
		totalSeats: 4,
		gameStyle: 'Northeast special',
		timing: 'Tea garden sessions',
		pricePerSession: 940,
		rating: 4.8,
		reviewCount: 28,
		bookingType: 'approval',
		amenities: ['Tea gardens', 'Northeast culture', 'Assam tea', 'Unique experience'],
		description: 'Unique Northeast experience with Assam tea and garden settings',
		hostType: 'home'
	},
	{
		id: 68,
		hostName: 'Raj',
		location: 'Amritsar Golden Temple Area, Punjab',
		city: 'Amritsar',
		seatsAvailable: 2,
		totalSeats: 4,
		gameStyle: 'Golden Temple spiritual',
		timing: 'Spiritual evening',
		pricePerSession: 920,
		rating: 4.9,
		reviewCount: 43,
		bookingType: 'instant',
		amenities: ['Golden Temple area', 'Spiritual setting', 'Punjabi culture', 'Sacred atmosphere'],
		description: 'Spiritual sessions near the sacred Golden Temple with divine atmosphere',
		hostType: 'home'
	},
	{
		id: 69,
		hostName: 'Neelam',
		location: 'Shimla Mall Road, Himachal Pradesh',
		city: 'Shimla',
		seatsAvailable: 1,
		totalSeats: 4,
		gameStyle: 'Hill station colonial',
		timing: 'Colonial evening',
		pricePerSession: 980,
		rating: 4.8,
		reviewCount: 37,
		bookingType: 'approval',
		amenities: ['Mall Road', 'Colonial heritage', 'Hill station', 'Cool climate'],
		description: 'Colonial-era charm sessions on Shimla\'s famous Mall Road',
		hostType: 'home'
	},
	{
		id: 70,
		hostName: 'Harsh',
		location: 'Udaipur City of Lakes, Rajasthan',
		city: 'Udaipur',
		seatsAvailable: 2,
		totalSeats: 4,
		gameStyle: 'Royal lakeside',
		timing: 'Lakeside sunset',
		pricePerSession: 1100,
		rating: 4.9,
		reviewCount: 52,
		bookingType: 'approval',
		amenities: ['City of Lakes', 'Royal setting', 'Sunset views', 'Romantic atmosphere'],
		description: 'Magical lakeside sunset sessions in the romantic City of Lakes',
		hostType: 'home'
	},
	{
		id: 71,
		hostName: 'Rohini',
		location: 'Thiruvananthapuram Kerala Capital',
		city: 'Thiruvananthapuram',
		seatsAvailable: 3,
		totalSeats: 4,
		gameStyle: 'Kerala traditional',
		timing: 'Traditional evening',
		pricePerSession: 950,
		rating: 4.7,
		reviewCount: 34,
		bookingType: 'instant',
		amenities: ['Kerala capital', 'Traditional setting', 'Evening sessions', 'Cultural heritage'],
		description: 'Traditional Kerala evening sessions in the state\'s beautiful capital',
		hostType: 'home'
	},
	{
		id: 72,
		hostName: 'Abhishek',
		location: 'Patna Historical Bihar',
		city: 'Patna',
		seatsAvailable: 2,
		totalSeats: 4,
		gameStyle: 'Historical Bihar',
		timing: 'Heritage evening',
		pricePerSession: 890,
		rating: 4.5,
		reviewCount: 24,
		bookingType: 'instant',
		amenities: ['Historical city', 'Bihar heritage', 'Evening sessions', 'Cultural roots'],
		description: 'Heritage evening sessions in Bihar\'s historic capital with cultural roots',
		hostType: 'home'
	}
];